name: auto_generate_storybook
description: "Auto Generates a Storybook from your golden tests."


version: 0.1.0


environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  args: ^2.3.2
  checked_yaml: ^2.0.2
  cli_util: ^0.4.0
  js: ^0.6.7
  html: ^0.15.4
  image: ^4.1.3
  universal_io: ^2.2.2
  meta: ^1.9.1
  json_annotation: ^4.8.0
  path: ^1.8.2
  yaml: ^3.1.2


  code_builder: ^4.10.0
  dart_style: ^2.3.4
  storybook_flutter: ^0.14.0
  recase: ^4.1.0
  source_gen: ^1.5.0
  analyzer: ^6.2.0
  logging: ^1.0.0

dev_dependencies:
  # Needed by build_version
  build_runner: ^2.4.8
  # https://pub.dev/packages/build_version
  build_version: ^2.1.1

  lints: ^1.0.0
